[package]
name = "mm-backend"
version = "0.1.0"
edition = "2021"
authors = ["Artemiy Granat <artemiigranat@gmail.com>"]

[dependencies]
actix-web = { version = "4.5.1", features = ["rustls"] }
anyhow = "1.0.81"
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.21"
